CREATE TABLE "REMOTE_DEVICE"
(
    "remoteDeviceId"  INTEGER NOT NULL,
    "remoteDeviceUrl" TEXT NOT NULL,
    "remoteDeviceToken" TEXT NOT NULL DEFAULT (HEX(RANDOMBLOB(16))),
    CONSTRAINT PK_REMOTE_DEVICE PRIMARY KEY ("remoteDeviceID"),
    CONSTRAINT UNIQUE_REMOTE_DEVICE_TOKEN UNIQUE("remoteDeviceToken")
);

CREATE TABLE "CHANNEL"
(
    "channelId" INTEGER NOT NULL,
    CONSTRAINT PK_CHANNEL PRIMARY KEY ("channelId")
);

CREATE TABLE "SUBSCRIBED"
(
    "remoteDeviceId" TEXT    NOT NULL,
    "channelId"      INTEGER NOT NULL,
    CONSTRAINT PK_SUBSCRIBED PRIMARY KEY ("remoteDeviceId", "channelId"),
    CONSTRAINT FK_SUBSCRIBED_REMOTE_DEVICE FOREIGN KEY ("remoteDeviceId") REFERENCES "REMOTE_DEVICE" ("remoteDeviceId"),
    CONSTRAINT FK_SUBSCRIBED_CHANNEL FOREIGN KEY ("channelId") REFERENCES "CHANNEL" ("channelId")
);

